#!/usr/bin/env sh

#
# This script is used to automatically update gitignore templates (via Heroku sheduler and etc.).
#

[ ! -n "${GITHUB_TOKEN+1}" ] && echo "Github token is not defined." >&2 && exit 1;

rm -rf _repo;

git clone --recursive 'https://github.com/voronkovich/gitignore.plugin.zsh' _repo \
    && cd _repo/templates \
    && git checkout master \
    && git pull \
    && cd .. \
    && git add . \
    && git config user.name 'Oleg Voronkovich' \
    && git config user.email 'oleg-voronkovich@yandex.ru' \
    && git commit -m '=^_^= Update templates' \
    && git push -q "https://voronkovich:${GITHUB_TOKEN}@github.com/voronkovich/gitignore.plugin.zsh";
