#!/usr/bin/env sh

#
# This script is used to automatically update gitignore templates (via Travis CI cronjob and etc.).
#

[ ! -n "${GITHUB_TOKEN+1}" ] && echo "Github token is not defined." >&2 && exit 1;

git submodule init \
    && git submodule update \
    && cd templates \
    && git checkout main \
    && cd .. \
    && git add . \
    && git config push.default simple \
    && git config user.name 'Oleg Voronkovich' \
    && git config user.email 'oleg-voronkovich@yandex.ru' \
    && git commit -m '=^_^= Update templates' \
    && git push -q "https://voronkovich:${GITHUB_TOKEN}@github.com/voronkovich/gitignore.plugin.zsh" HEAD:master
